#配置dev环境
spring:
  profiles: dev
  application:
    name: kfjmsc-eurekaServer-config

server:
  port: 8400

eureka:
  instance:
    hostname: localhost #指定Eureka主机
  client:
    register-with-eureka: false  #指定当前主机是否需要向注册中心注册（因为当前主机是server，不是client）
    fetch-registry: false #指定当前主机是否需要获取注册信息（不用，因为当前主机是server，不是client）
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
#配置test环境
spring:
  profiles: test
  application:
    name: kfjmsc-eurekaServer-config

server:
  port: 8500

eureka:
  instance:
    hostname: localhost #指定Eureka主机
  client:
    register-with-eureka: false  #指定当前主机是否需要向注册中心注册（因为当前主机是server，不是client）
    fetch-registry: false #指定当前主机是否需要获取注册信息（不用，因为当前主机是server，不是client）
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/